@startuml





/' Objects '/

class Group {
	+Group()
	+Group(Attributes attributes)
	+~Group()
	-attributes : Attributes
	+getAttributes() : Attributes {query}
	+getClass() : std::string {query}
	+getElements() : std::vector<SVGElement*> {query}
	-shapes : std::vector<SVGElement*>
	+addElement(SVGElement* shape) : void
	+printData() : void {query}
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
