@startuml
class "Viewer" as C_0000222566171378319347
class C_0000222566171378319347 {
+Viewer() = deleted : void
-Viewer() : void
..
+operator=() = deleted : void
..
{static} +getInstance() : Viewer *
+handleDragging() : void
+handleEvents() : void
-moveView() : void
-rotate() : void
-startDragging() : void
-stopDragging() : void
-zoom() : void
__
{static} -instance : Viewer *
-is_mouse_dragging : bool
-last_mouse_position : sf::Vector2i
-view : sf::View &
-window : sf::RenderWindow &
}
C_0000222566171378319347 --> C_0000222566171378319347 : -instance

'Generated with clang-uml, version 0.4.1
'LLVM version Ubuntu clang version 15.0.7
@enduml
