@startuml





/' Objects '/

class Viewer {
	-Viewer()
	+~Viewer()
	-last_mouse_pos : POINT
	+{static} getInstance() : Viewer*
	-is_dragging : bool
	+needs_repaint : bool
	+offset_x : float
	+offset_y : float
	+rotate_angle : float
	+zoom_factor : float
	-{static} instance : static Viewer*
	-handleKeyDown(WPARAM wParam) : void
	+handleKeyEvent(WPARAM wParam) : void
	-handleLeftButtonDown(LPARAM lParam) : void
	-handleLeftButtonUp() : void
	+handleMouseEvent(UINT message, WPARAM wParam, LPARAM lParam) : void
	-handleMouseMove(LPARAM lParam) : void
	-handleMouseWheel(WPARAM wParam) : void
}





/' Inheritance relationships '/




/' Aggregation relationships '/

.Viewer --> .Viewer : -instance






/' Nested objects '/



@enduml
