name: build
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install cmake clang-format
          sudo apt-get install libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libxrandr-dev libfreetype6-dev libjpeg8-dev libsndfile1-dev libopenal-dev libudev-dev libxinerama-dev libxcursor-dev libxi-dev
          sudo apt-get install wine64
      - name: Run clang-format
        run: clang-format --dry-run --Werror src/**/*.*pp
      - name: Run CMake
        run: cmake -S. -Bbuild
      - name: Run Make
        run: make -Cbuild
