name: build
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install cmake clang-format clang-tidy
          sudo apt-get install libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libxrandr-dev libfreetype6-dev libjpeg8-dev libsndfile1-dev libopenal-dev libudev-dev libxinerama-dev libxcursor-dev libxi-dev
      - name: Install SFML
        run: |
          git clone https://github.com/SFML/SFML.git SFML
          cd SFML
          mkdir build && cd build
          cmake -DBUILD_SHARED_LIBS=ON ..
          make
          sudo make install
          cd ../..
      - name: Install pugixml
        run: |
          git clone https://github.com/zeux/pugixml.git pugixml
          cd pugixml
          mkdir build && cd build
          cmake -DBUILD_SHARED_LIBS=ON ..
          make
          sudo make install
          cd ../..
      - name: Run clang-format
        run: clang-format --dry-run --Werror src/*
      - name: Run CMake
        run: cmake -S. -Bbuild
      - name: Run Make
        run: make -Cbuild
